<?php defined('_RTMEXEC') or die('No direct script access.');

return array(
                  'registration' => array('registration_token'=>array('valid' => array(),
                                                                      'type' =>'hidden',
                                                                      'id'=>'token',
                                                                      'val' =>'',
                                                                      'placeholder' =>'',
                                                                      'class' =>''
                                           ),
                                           'user_email'=>array('valid' => array('required'=>'user_email_required_error',
                                                                                'email'=>'user_email_email_error', 
                                                                                'unique'=>'user_email_unique_error'),
                                                                'type' =>'text',
                                                                'id'=>'email',
                                                                'val' =>'',
                                                                'placeholder' =>'',
                                                                'class' =>'form-control',
                                                                'disabled'=>0
                                            ),
                    
                                          'user_first_name'=>array('valid' => array('required'=>'user_first_name_required_error',
                                                                                    'name'=>'user_first_name_name_error'),
                                                                   'type' =>'text',
                                                                   'id'=>'first_name',
                                                                   'val' =>'',
                                                                   'placeholder' =>'',
                                                                   'class' =>'form-control',
                                                                   'disabled'=>0
                                            ),
                    
                                           'user_last_name'=>array('valid' => array('required'=>'user_last_name_required_error',
                                                                                    'name'=>'user_last_name_name_error'),
                                                                   'type' =>'text',
                                                                   'id'=>'last_name',
                                                                   'val' =>'',
                                                                   'placeholder' =>'',
                                                                   'class' =>'form-control',
                                                                   'disabled'=>0
                                           )
                                        ),
		   'login' => array('login_token'=>array('valid' => array(),
                                                                'type' =>'hidden',
                                                                'id'=>'token',
                                                                'val' =>'',
                                                                'placeholder' =>'',
                                                                'class' =>''
                                    ),
                                    'user_email'=>array('valid' => array('required'=>'user_email_required_error',
                                                                         'email'=>'user_email_email_error', 
                                                                         'exist'=>'user_email_exist_error'),
                                                        'type' =>'text',
                                                        'id'   =>'email',
                                                        'val'  =>'',
                                                        'placeholder' =>'',
                                                        'class' =>'form-control',
                                                        'disabled'=>0
                                    ),
                                    'user_pass' =>array('valid' => array('required'=>'user_pass_required_error'),
                                                        'type' =>'password',
                                                        'id'   =>'pass',
                                                        'val'  =>'',
                                                        'placeholder' =>'',
                                                        'class' =>'form-control',
                                                        'disabled'=>0)
                                    ),
    
                   'profile' => array('profile_token'=>array('valid' => array(),
                                                             'type' =>'hidden',
                                                             'id'=>'token',
                                                             'val' =>'',
                                                             'placeholder' =>'',
                                                             'class' =>'',
                                                             'disabled'=>0
                                    ),
                                    'user_email'=>array('valid' => array('required'=>'user_email_required_error',
                                                                         'email'=>'user_email_email_error', 
                                                                         'exist'=>'user_email_exist_error', 
                                                                         'uniqother'=>'user_email_uniqother_error'),
                                                        'type' =>'text',
                                                        'id'   =>'email',
                                                        'val'  =>'',
                                                        'placeholder' =>'',
                                                        'class' =>'form-control',
                                                        'disabled'=>1
                                    ),
                       
                                    'user_fname'=>array('valid' => array('required'=>'user_first_name_required_error',
                                                                                    'name'=>'user_first_name_name_error'),
                                                                   'type' =>'text',
                                                                   'id'=>'first_name',
                                                                   'val' =>'',
                                                                   'placeholder' =>'',
                                                                   'class' =>'form-control',
                                                                      'disabled'=>0
                                    ),
                       
                                    'user_mname'=>array('valid' => array('name'=>'user_middle_name_name_error'),
                                                                   'type' =>'text',
                                                                   'id'=>'first_name',
                                                                   'val' =>'',
                                                                   'placeholder' =>'',
                                                                   'class' =>'form-control',
                                                                   'disabled'=>0
                                    ),
                    
                                    'user_lname'=>array('valid' => array('required'=>'user_last_name_required_error',
                                                                                    'name'=>'user_last_name_name_error'),
                                                                   'type' =>'text',
                                                                   'id'=>'last_name',
                                                                   'val' =>'',
                                                                   'placeholder' =>'',
                                                                   'class' =>'form-control',
                                                                   'disabled'=>0
                                    ),
                       
                                    'user_phone'=>array('valid' => array('required'=>'user_phone_required_error',
                                                                                     'phone'=>'user_phone_phone_error',
                                                                                     'uniqother'=>'user_email_uniqother_error'),
                                                                   'type' =>'text',
                                                                   'id'=>'phone',
                                                                   'val' =>'',
                                                                   'placeholder' =>'',
                                                                   'class' =>'form-control',
                                                                   'disabled'=>0
                                    ),
                       
                                    'user_state'=>array('valid' => array('required'=>'user_state_required_error'),
                                                                   'type' =>'select',
                                                                   'id'=>'state',
                                                                   'val' =>'',
                                                                   'options' =>array('Russia'=>'Россия',
                                                                                     'Ukraine'=>'Украина'
                                                                                    ),
                                                                   'class' =>'form-control',
                                                                   'disabled'=>0
                                    ),
                        
                                    'user_region'=>array('valid' => array('name'=>'user_region_name_error'),
                                                                   'type' =>'text',
                                                                   'id'=>'region',
                                                                   'val' =>'',
                                                                   'placeholder' =>'',
                                                                   'class' =>'form-control',
                                                                   'disabled'=>0
                                    ),
                       
                                    'user_city'=>array('valid' => array('name'=>'user_city_name_error'),
                                                                   'type' =>'text',
                                                                   'id'=>'city',
                                                                   'val' =>'',
                                                                   'placeholder' =>'',
                                                                   'class' =>'form-control',
                                                                   'disabled'=>0
                                    ),
                       
                                    'user_zip_code'=>array('valid' => array('zip'=>'user_zip_code_error'),
                                                                   'type' =>'text',
                                                                   'id'=>'zip_code',
                                                                   'val' =>'',
                                                                   'placeholder' =>'',
                                                                   'class' =>'form-control',
                                                                   'disabled'=>0
                                    ),
                       
                                    'user_address'=>array('valid' => array('address'=>'user_address_error'),
                                                                   'type' =>'text',
                                                                   'id'=>'address',
                                                                   'val' =>'',
                                                                   'placeholder' =>'',
                                                                   'class' =>'form-control',
                                                                   'disabled'=>0
                                    ),
                        ),
    
                   'contact' => array('contact_token'=>array('valid' => array(),
                                                             'type' =>'hidden',
                                                             'id'=>'token',
                                                             'val' =>'',
                                                             'placeholder' =>'',
                                                             'class' =>''
                                    ),
                                    'user_email'=>array('valid' => array('required'=>'user_email_required_error',
                                                                         'email'=>'user_email_format_error'),
                                                        'type' =>'text',
                                                        'id'=>'email',
                                                        'val' =>'',
                                                        'placeholder' =>'',
                                                        'class' =>'form-control',
                                                        'disabled'=>0
                                    ),
                                    'email_subject'=>array('valid' => array('required'=>'email_subject_required_error'),
                                                           'type' =>'select',
                                                           'id'   =>'subject',
                                                           'val'  =>'',
                                                           'options' =>'',
                                                           'placeholder' =>'',
                                                           'class' =>'form-control',
                                                           'disabled'=>0
                                    ),
                                    'email_body' =>array('valid' => array('required'=>'email_text_required_error'),
                                                        'type' =>'textarea',
                                                        'id'   =>'ebody',
                                                        'val'  =>'',
                                                        'placeholder' =>'',
                                                        'class' =>'form-control',
                                                        'rows' => 10,
                                                        'disabled'=>0)
                                    ),
                   'controlin' => array('controlin_token'=>array('valid' => array(),
                                                                'type' =>'hidden',
                                                                'id'=>'token',
                                                                'val' =>'',
                                                                'placeholder' =>'',
                                                                'class' =>''
                                    ),
                                    'user_email'=>array('valid' => array('required'=>'user_email_required_error',
                                                                         'email'=>'user_email_email_error', 
                                                                         'exist'=>'user_email_exist_error'),
                                                        'type' =>'text',
                                                        'id'   =>'email',
                                                        'val'  =>'',
                                                        'placeholder' =>'',
                                                        'class' =>'form-control',
                                                        'disabled'=>0
                                    ),
                                    'user_pass' =>array('valid' => array('required'=>'user_pass_required_error'),
                                                        'type' =>'password',
                                                        'id'   =>'pass',
                                                        'val'  =>'',
                                                        'placeholder' =>'',
                                                        'class' =>'form-control',
                                                        'disabled'=>0)
                                    ),
                   'pass' => array('pass_token'=>array('valid' => array(),
                                                                'type' =>'hidden',
                                                                'id'=>'token',
                                                                'val' =>'',
                                                                'placeholder' =>'',
                                                                'class' =>'',
                                                                'disabled'=>0
                                    ),
                                    'user_pass' =>array('valid' => array('required'=>'user_pass_required_error'),
                                                        'type' =>'password',
                                                        'id'   =>'pass',
                                                        'val'  =>'',
                                                        'placeholder' =>'',
                                                        'class' =>'form-control',
                                                        'disabled'=>0),
                            
                                    'user_newpass' =>array('valid' => array('required'=>'user_pass_required_error',
                                                                            'passwd'  =>'user_passwd_error'),
                                                        'type' =>'password',
                                                        'id'   =>'newpass',
                                                        'val'  =>'',
                                                        'placeholder' =>'',
                                                        'class' =>'form-control',
                                                        'disabled'=>0),
                            
                                    'user_confpass' =>array('valid' => array('required'=>'user_pass_required_error',
                                                                             'passwd'  =>'user_passwd_error'),
                                                        'type' =>'password',
                                                        'id'   =>'confpass',
                                                        'val'  =>'',
                                                        'placeholder' =>'',
                                                        'class' =>'form-control',
                                                        'disabled'=>0)
                                    ),
                    'authkey' => array('authkey_token'=>array('valid' => array(),
                                                              'type' =>'hidden',
                                                              'id'=>'token',
                                                              'val' =>'',
                                                              'placeholder' =>'',
                                                              'class' =>''
                                    ),
                                    'key_acc'=>array('valid' => array('required'=>'key_acc_required_error'),
                                                     'type' =>'text',
                                                     'id'   =>'akey',
                                                     'val'  =>'',
                                                     'placeholder' =>'',
                                                     'class' =>'form-control',
                                                     'disabled'=>0
                                    ),
                                    'hash_key' =>array('valid' => array(),
                                                       'type' =>'hidden',
                                                       'id'   =>'hkey',
                                                       'val'  =>'',
                                                       'placeholder' =>'',
                                                       'class' =>'form-control',
                                                       'disabled'=>0)
                                    ),
                    'pagscrl' => array('pagscrl_token'=>array('valid' => array(),
                                                             'type' =>'hidden',
                                                             'id'=>'token',
                                                             'val' =>'',
                                                             'placeholder' =>'',
                                                             'class' =>''
                                    ),
                                    
                                    'page_content' =>array('valid' => array('required'=>'page_content_required_error'),
                                                        'type' =>'textarea',
                                                        'id'   =>'pcontent',
                                                        'val'  =>'',
                                                        'placeholder' =>'',
                                                        'class' =>'form-control',
                                                        'rows' => 20,
                                                        'disabled'=>0)
                                    ),
    
                    'newgallercrl' => array('newgallercrl_token'=>array('valid' => array(),
                                                              'type' =>'hidden',
                                                              'id'=>'token',
                                                              'val' =>'',
                                                              'placeholder' =>'',
                                                              'class' =>''
                                    ),
                       
                                    'gall_photo' =>array('valid' => array(),
                                                     'type' =>'file',
                                                     'id'   =>'',
                                                     'val'  =>'',
                                                     'placeholder' =>'',
                                                     'class' =>'form-control',
                                                     'disabled'=>0)
                                    )
                 );
